// All user-facing copy. Sentence-case actions, Title Case headings, errors start with what happened.
// Brand text (name/tagline/product label) is imported from @shared/brand - never duplicate here.

import { BRAND } from '@shared/brand';

export const STRINGS = {
  brand: {
    name:         BRAND.name,
    tagline:      BRAND.tagline,
    productLabel: BRAND.productLabel,
    fullTitle:    BRAND.fullTitle,
  },

  nav: {
    cashier:    'Cashier',
    dashboard:  'Dashboard',
    sales:      'Sales',
    customers:  'Customers',
    products:   'Products',
    users:      'Staff',
    settings:   'Settings',
    logout:     'Log out',
    register:   'Register #01',
    account:    'Account',
  },

  auth: {
    loginTitle:     'Sign in to your store',
    loginSubtitle:  'Enter your credentials to continue.',
    username:       'Username',
    password:       'Password',
    signIn:         'Sign in',
    signingIn:      'Signing in…',
    demoHint:       'Demo tenants · myntra/myntra123 · flipkart/flipkart123 · walmart/walmart123 · SaaS owner · vendor/vendor123',
    invalid:        'Invalid username or password.',
    inactive:       'This account is inactive. Contact your admin.',
    suspended:      'This store has been suspended by the vendor. Please reach out to support.',
    loggedOut:      'You have been signed out.',
    sessionExpired: 'Your session has expired. Please sign in again.',    welcome:        (name: string) => `Welcome, ${name}!`,  },

  cashier: {
    pageTitle:        'Cashier Terminal',
    pageSubtitle:     'Ring up items and check out customers.',
    searchPlaceholder:'Search by product name…',
    clearSearch:      'Clear search',
    emptyResults:     'No products match your search.',
    emptyResultsHint: 'Try a different keyword or category.',
    addToCart:        'Add',
    inStock:          'In stock',
    lowStock:         'Low',
    cartTitle:        'Current Sale',
    cartEmpty:        'Cart is empty',
    cartEmptyHint:    'Tap a product on the left to add it.',
    clearCart:        'Clear',
    charge:           'Charge',
    itemsSuffix:      'items',
    itemSuffix:       'item',
    decreaseQty:      'Decrease quantity',
    increaseQty:      'Increase quantity',
    removeLine:       'Remove item',
    subtotal:         'Subtotal',
    tax:              'Tax',
    total:            'Total',
    noActiveStore:    'No active store selected — cannot record lending sale.',
  },

  payment: {
    heading:            'Choose payment method',
    subheading:         'Select how the customer will pay.',
    methodCash:         'Cash',
    methodCashHint:     'Pay with physical currency.',
    methodCard:         'Card',
    methodCardHint:     'Debit or credit card.',
    methodLending:      'Lending',
    methodLendingHint:  'Buy now, pay later — mobile required.',
    mobileLabel:        'Customer mobile number',
    mobileHint:         '10-digit number for lending record & receipt.',
    mobileError:        "That doesn't look like a valid 10-digit number.",
    cancel:             'Cancel',
    submit:             'Complete sale',
    submitting:         'Processing…',
  },

  receipt: {
    successHeading: 'Payment successful',
    successBody:    'The sale has been recorded.',
    invoice:        'Invoice',
    customer:       'Customer',
    payment:        'Payment method',
    dateLabel:      'Date',
    itemsSold:      'Items sold',
    uniqueItems:    'Unique items',
    totalUnits:     'Total units',
    amountPaid:     'Amount paid',
    thankYou:       'Thank you.',
    returnPolicy:   'No Returns',
    print:          'Print receipt',
    newSale:        'Start new sale',
  },

  dashboard: {
    pageTitle:      'Sales Dashboard',
    pageSubtitle:   'Live view of everything sold today.',
    kpiRevenue:     'Revenue today',
    kpiSales:       'Sales completed',
    kpiUnits:       'Units sold',
    kpiUniqueSku:   'Unique SKUs',
    kpiLendingWO:   'Lending balance',

    recentSalesTitle:     'Recent sales',
    recentSalesEmpty:     'No sales yet — head to the Cashier to ring one up.',
    columnInvoice:        'Invoice',
    columnTime:           'Time',
    columnItems:          'Items',
    columnPayment:        'Payment',
    columnCustomer:       'Customer',
    columnTotal:          'Total',

    topProductsTitle:  'Top-selling products',
    topProductsEmpty:  'No products sold yet.',
    columnRank:        '#',
    columnProduct:     'Product',
    columnSold:        'Units sold',
    columnRevenue:     'Revenue',

    inventoryTitle:    'Inventory movement',
    inventoryEmpty:    'No inventory movement yet.',
    columnSku:         'SKU',
    columnCategory:    'Category',
    columnStock:       'Stock left',
    columnMovement:    'Sold today',
  },

  products: {
    pageTitle:     'Products',
    pageSubtitle:  'Manage your product catalog and stock levels.',
    addNew:        'Add product',
    editHeading:   'Edit product',
    createHeading: 'Add a new product',
    empty:         'No products yet.',
    emptyHint:     'Click “Add product” to get started.',
    columnSku:     'SKU',
    columnName:    'Name',
    columnPrice:   'Price',
    columnStock:   'Stock',
    columnStatus:  'Status',
    active:        'Active',
    inactive:      'Inactive',
    edit:          'Edit',
    deactivate:    'Deactivate',
    activate:      'Activate',
    fieldSku:      'SKU',
    fieldName:     'Name',
    fieldPrice:    'Price',
    fieldStock:    'Stock',
    fieldCategory: 'Category',
    fieldTone:     'Colour tone',
    save:          'Save',
    saving:        'Saving…',
    saved:         'Product saved.',
    deleteConfirm: 'Deactivate this product? It will be hidden from the Cashier terminal.',
    duplicateSku:      'A product with that SKU already exists.',
    searchPlaceholder: 'Search by name or SKU…',
    clearSearch:       'Clear search',
    emptySearch:       'No products match your search',
    emptySearchHint:   'Try a different name or SKU.',
    skuNameRequired:   'SKU and name are required.',
    reactivated:       (name: string) => `${name} reactivated.`,
  },

  customers: {
    pageTitle:      'Customers',
    pageSubtitle:   'Look up shoppers, track lending balances, record payments.',
    addNew:         'Add customer',
    createHeading:  'Add a new customer',
    editHeading:    'Edit customer',
    empty:          'No customers yet.',
    emptyHint:      'Add one, or the next Lending sale will create one automatically.',
    columnName:     'Name',
    columnMobile:   'Mobile',
    columnEmail:    'Email',
    columnBalance:  'Lending balance',
    columnSince:    'Customer since',
    columnActions:  'Actions',
    view:           'View',
    edit:           'Edit',
    fieldName:      'Name',
    fieldMobile:    'Mobile',
    fieldEmail:     'Email (optional)',
    fieldNotes:     'Notes (optional)',
    save:           'Save',
    duplicateMobile:'A customer with that mobile already exists.',
    searchPlaceholder:'Search by name or mobile…',
    detailTitle:     'Customer profile',
    balanceHeading:  'Outstanding lending balance',
    recordPayment:   'Record a payment',
    recordPaymentHint:'Enter the amount the customer just paid to reduce their balance.',
    paymentAmount:   'Amount paid',
    paymentMethod:   'Method',
    paymentNotes:    'Notes (optional)',
    submitPayment:   'Record payment',
    paymentSuccess:  'Payment recorded.',
    paymentTooHigh:  'Amount exceeds the outstanding balance.',
    paymentInvalid:  'Enter a valid amount greater than 0.',
    paymentHistory:  'Payment history',
    paymentEmpty:    'No payments recorded yet.',
    saleHistory:          'Sale history',
    saleHistoryEmpty:     'No sales recorded for this customer yet.',
    backToList:           'All customers',
    nameRequired:         'Name is required.',
    added:                'Customer added.',
    clearSearch:          'Clear search',
    emptySearch:          'No customers match your search',
    emptySearchHint:      'Try a different name or mobile number.',
    notFound:             'Customer not found',
    notFoundHint:         'It may have been deleted from this browser.',
    deleteTitle:          'Delete customer?',
    deleteLabel:          'Delete customer',
    deleteConfirmBalance: (name: string, balance: string) =>
      `${name} has an outstanding lending balance of ${balance}. Clear it before deleting.`,
    deleteConfirmClean:   (name: string) =>
      `${name} and all their payment history will be permanently removed. This can't be undone.`,
    hasBalanceError:      'Cannot delete — outstanding balance.',
    notFoundError:        'Customer not found.',
    deleted:              (name: string) => `${name} deleted.`,
    sectionProfile:       'Profile',
    outstandingBalance:   'Outstanding balance',
    saleComplete:         'Complete',
    columnDate:           'Date',
    columnMethodLabel:    'Method',
    columnReceivedBy:     'Received by',
    columnNotes:          'Notes',
    columnAmount:         'Amount',
    columnInvoice:        'Invoice',
    columnItems:          'Items',
    columnSalePayment:    'Payment',
    columnStatus:         'Status',
    columnTotal:          'Total',
  },

  sales: {
    pageTitle:      'Sales history',
    pageSubtitle:   'Every sale, filterable, exportable, voidable.',
    empty:          'No sales recorded yet.',
    emptyHint:      'Head to the Cashier to ring one up.',
    filterAll:      'All',
    filterCash:     'Cash',
    filterCard:     'Card',
    filterLending:  'Lending',
    filterVoided:   'Voided only',
    filterActive:   'Not voided',
    view:           'View',
    void:           'Void',
    voidHeading:    'Void this sale?',
    voidHint:       'The sale stays in history for audit but stops counting towards revenue.',
    voidReason:     'Reason (required)',
    voidConfirm:    'Void sale',
    voidedBadge:    'Voided',
    voidSuccess:    'Sale voided.',
    detailTitle:    'Sale detail',
    backToList:     'All sales',
    notFound:       'Sale not found',
    notFoundHint:   'It may have been deleted.',
    sectionSummary: 'Summary',
    complete:       'Complete',
    labelCashier:   'Cashier',
    labelVoidReason:'Void reason',
    units:          (n: number | string) => `${n} units`,
    voidedOn:       (date: string) => `on ${date}`,
    columnProduct:  'Product',
    columnSku:      'SKU',
    columnQty:      'Qty',
    columnUnitPrice:'Unit price',
    columnLineTotal:'Line total',
  },

  users: {
    pageTitle:      'Staff',
    pageSubtitle:   'Manage who can access the terminal.',
    addNew:         'Invite user',
    createHeading:  'Invite a new user',
    editHeading:    'Edit user',
    empty:          'No staff yet — invite your first cashier.',
    columnName:     'Name',
    columnUsername: 'Username',
    columnRole:     'Role',
    columnStatus:   'Status',
    columnActions:  'Actions',
    fieldName:      'Full name',
    fieldUsername:  'Username',
    fieldPassword:  'Password',
    fieldRole:      'Role',
    roleAdmin:      'Admin',
    roleCashier:    'Cashier',
    active:         'Active',
    inactive:       'Inactive',
    edit:           'Edit',
    deactivate:     'Deactivate',
    activate:       'Activate',
    save:           'Save',
    duplicateUser:  'That username is already in use.',
    weakPassword:   'Password must be at least 8 characters.',
    cannotDeactivateSelf:  'You cannot deactivate your own account.',
    forbidden:             'Only admins can manage staff.',
    noStore:               'Please pick a store for this user.',
    invited:               (name: string) => `Invited ${name}.`,
    updated:               'User updated.',
    reactivated:           (name: string) => `${name} reactivated.`,
    deactivated:           (name: string) => `${name} deactivated.`,
    pageSubtitleSuper:     'All staff across every store.',
    columnStore:           'Store',
    globalRole:            '— (global)',
    joinedOn:              (date: string) => `joined ${date}`,
    deactivateTitle:       'Deactivate user?',
    deactivateMessage:     (name: string) =>
      `${name} will no longer be able to sign in. You can reactivate them later.`,
    superAdminRole:        'Super admin',
    pickStore:             '— Pick a store —',
    passwordHintEdit:      'Leave blank to keep the current password.',
    passwordHintNew:       'Minimum 8 characters.',
  },

  settings: {
    pageTitle:     'Settings',
    pageSubtitle:  'Your receipt template and local data controls.',
    save:          'Save changes',
    saved:         'Settings saved.',
    storeName:     'Store name',
    address:       'Address',
    phone:         'Phone',
    gstin:         'Tax ID / GSTIN',
    taxRate:       'Tax rate (%)',
    currency:      'Currency (ISO 4217)',
    receiptFooter: 'Receipt footer message',
    profileHeading:  'Store profile',
    profileLockNote: 'These fields are managed by your SaaS provider so past invoices and analytics stay consistent. Contact them to make changes.',
    receiptHeading:  'Receipt template',
    receiptHint:     'Shown at the bottom of every printed receipt.',
    dangerHeading: 'Danger zone',
    dangerHint:    'Wipe all locally stored data. Only affects this browser.',
    wipeAll:       'Reset all local data',
    wipeConfirm:   'This will delete all sales, customers, products and settings from this browser. Continue?',
    wipeDone:      'All local data cleared. Reloading…',
    forbidden:     'Only admins can change settings.',
  },

  common: {
    save:        'Save',
    cancel:      'Cancel',
    close:       'Close',
    delete:      'Delete',
    confirm:     'Confirm',
    yes:         'Yes',
    no:          'No',
    back:        'Back',
    loading:     'Loading…',
    actions:     'Actions',
    complete:    'Complete',
    clearSearch: 'Clear search',
  },

  errors: {
    generic:        'Something went wrong. Try again.',
    emptyCart:      'Add at least one product before charging.',
    mobileRequired: 'Mobile number is required for lending sales.',
    outOfStock:     'Not enough stock available.',
    notFound:       'That record no longer exists.',
    forbidden:      "You don't have permission to do that.",

    /* --- App-level failure UIs ------------------------------------------ */
    boundaryTitle:      'Something broke on this screen',
    boundaryHint:       'The rest of the app is fine — you can try this screen again, jump home, or fully reload.',
    tryAgain:           'Try again',
    goHome:             'Go home',
    reload:             'Reload app',
    technicalDetails:   'Technical details',

    bootLoading:        'Warming up your store…',
    bootFailedTitle:    "We couldn't open your store's database",
    bootFailedHint:     'This usually means the browser is blocking IndexedDB (private mode, cookies disabled, or storage full). Try a normal window, or clear site data and reload.',
    bootRetry:          'Retry',

    notFoundTitle:      'Page not found',
    notFoundHint:       "We couldn't find the page you were looking for.",
    backToCashier:      'Back to cashier',

    // Global async failures
    unhandledRejection: 'A background task failed. Please try again.',
    scriptError:        'A script error occurred. Please reload.',
  },

  ariaLabels: {
    openCart:         'Open cart',
    closePayment:     'Close payment dialog',
    closeReceipt:     'Close receipt dialog',
    navigate:         'Primary navigation',
    userMenu:         'Account menu',
    closeModal:       'Close dialog',
  },
} as const;
