// ::: Code Generated by Copilot 7d154f0c-3b26-4d6e-8d85-0b51e380a532. This comment will be removed automatically after the file is saved :::
// catalog.ts - product-domain enums and constants.

// PRODUCTION - source-of-truth vocabulary for Product's category+tone unions.

// If you're looking for the demo product list, it moved to
// @shared/fixtures/products.ts along with the rest of the seed data.
import type { Product } from './types';

export const CATEGORY_FILTERS: readonly ('All' | Product['category'])[] = [
  'All', 'Grocery', 'Produce', 'Beverages', 'Snacks',
  'Household', 'Personal', 'Meat', 'Frozen', 'Electronics', 'Other',
  'Biryani', 'Rice Items', 'Gravies', 'Parotta & Roti', 'Rolls', 'Kebabs', 'Tandoori Items',
];

export const ALL_CATEGORIES: readonly Product['category'][] = [
  'Grocery', 'Produce', 'Beverages', 'Snacks',
  'Household', 'Personal', 'Meat', 'Frozen', 'Electronics', 'Other',
  'Biryani', 'Rice Items', 'Gravies', 'Parotta & Roti', 'Rolls', 'Kebabs', 'Tandoori Items',
];

export const ALL_TONES: readonly Product['tone'][] = [
  'sky', 'amber', 'yellow', 'red', 'stone', 'orange', 'brown', 'rose', 'slate',
];


export const TAX_RATE = 0.0825;
