// ::: Code Generated by Copilot 7d154f0c-3b26-4d6e-8d85-0b51e380a532. This comment will be removed automatically after the file is saved :::
// Domain types - shared vocabulary. Every entity carries id+createdAt; add tenantId once backend arrives.

// Shared primitives
export type Iso8601 = string;
export type PaymentMethod = 'cash' | 'card' | 'lending' | 'cod' | 'online';

// Where the sale originated. Counter = staff rang it up at the till.
// Online = customer placed it via the tenant's storefront (delivery flow).
export type SaleChannel = 'counter' | 'online';

// Lifecycle for online orders (null for counter sales).
export type OrderStatus =
  | 'placed'            // customer just submitted; staff hasn't seen it yet
  | 'confirmed'         // staff acknowledged; stock reserved
  | 'packing'           // being prepared
  | 'out_for_delivery'  // rider has it
  | 'delivered'         // handed off; payment collected (COD) or already captured (online)
  | 'cancelled';        // by customer OR staff — see cancelledBy

export interface DeliveryAddress {
  readonly line1: string;
  readonly line2: string;
  readonly city: string;
  readonly pincode: string;
  readonly landmark: string;
}

export interface OrderStatusEvent {
  readonly status: OrderStatus;
  readonly at: Iso8601;
  readonly by: string;  // 'customer' | staff username
  readonly note: string;
}

// Stores (multi-tenant)
export interface Store {
  readonly id: string;
  readonly name: string;
  readonly city: string;
  readonly phone: string;
  readonly address: string;
  // Sales tax rate as a decimal (e.g. 0.0825 = 8.25%).
  readonly taxRate: number;
  // ISO 4217 currency code.
  readonly currency: string;
  readonly active: boolean;
  // Vendor-controlled lifecycle: 'suspended' stores can't log in. Defaults to 'active'.
  readonly status: 'active' | 'suspended';
  readonly createdAt: Iso8601;
}

// All non-store entities carry a storeId (required, never null).
//  Users too — every user belongs to exactly one store.
export type StoreScope = string;

// Discriminated status union for async state — enforces "handle all 4 states".
// (§2 RULE — never render on data alone; render on state.)
export type AsyncStatus<T, E = string> =
  | { readonly kind: 'idle' }
  | { readonly kind: 'loading' }
  | { readonly kind: 'success'; readonly data: T }
  | { readonly kind: 'error';   readonly error: E };

// Products
export type ProductCategory =
  | 'Grocery' | 'Produce' | 'Beverages' | 'Snacks'
  | 'Household' | 'Personal' | 'Meat' | 'Frozen' | 'Electronics' | 'Other'
  | 'Biryani' | 'Rice Items' | 'Gravies' | 'Parotta & Roti' | 'Rolls' | 'Kebabs' | 'Tandoori Items';

// Tone controls the pastel colour tile behind each product monogram.
export type BadgeTone =
  | 'sky' | 'amber' | 'yellow' | 'red' | 'stone'
  | 'orange' | 'brown' | 'rose' | 'slate';

export interface Product {
  readonly id: string;
  readonly sku: string;
  readonly name: string;
  readonly price: number;
  readonly category: ProductCategory;
  readonly tone: BadgeTone;
  // Total stock available (unit count).
  readonly stock: number;
  readonly active: boolean;
  readonly createdAt: Iso8601;
  // Store that owns this product.
  readonly storeId: string;
  // Outlet within the store. As of v8 EVERY product belongs to exactly one
  // outlet - menus are managed per-branch. Optional in the type only for
  // back-compat with legacy rows read during migration; the bootstrap
  // migration backfills every existing row to the first outlet of its
  // storeId, and all writes require it.
  readonly outletId?: string;

  // * Optional photo URL — populated in fixture tenants; future: served by product API.
  readonly image?: string;
}

// Sales
export interface SaleLine {
  readonly productId: string;
  readonly sku: string;
  readonly name: string;
  readonly tone: BadgeTone;
  readonly unitPrice: number;         // final unit price after variant/mod deltas
  readonly quantity: number;
  readonly lineTotal: number;         // (unitPrice * quantity) - lineDiscount

  // -- Cashier extensions (all optional for back-compat with old sales) ---
  // Original list price before variant / modifier deltas. Populated only *  when the line was configured through the modifier picker.
  readonly originalUnitPrice?: number;
  // * Variant selected (e.g. "Half", "Full").
  readonly variantId?: string;
  readonly variantLabel?: string;
  // * Chosen modifier options (extra cheese, no onions, etc.).
  readonly modifiers?: readonly SaleLineModifier[];
  // * Discount applied on this line specifically (positive currency amount).
  readonly lineDiscount?: number;
  readonly lineDiscountReason?: string;
  // * Note the cashier attached (e.g. "allergy: peanuts").
  readonly note?: string;
}

export interface SaleLineModifier {
  readonly modifierId: string;
  readonly modifierName: string;
  readonly optionId: string;
  readonly optionName: string;
  readonly priceDelta: number;
}

// * A single payment tender on a split-payment sale.
export interface SalePayment {
  readonly method: PaymentMethod;
  readonly amount: number;
  readonly reference?: string;      // e.g. UPI txn id, last-4 card
}

// * An additional charge line (service / packaging / delivery / etc).
export interface SaleCharge {
  readonly chargeId: string;
  readonly name: string;
  readonly amount: number;
  readonly taxable: boolean;
}

// * Bill-level discount snapshot.
export interface SaleBillDiscount {
  readonly discountId: string | null;   // null = ad-hoc manual discount
  readonly name: string;
  readonly type: 'percent' | 'flat';
  readonly value: number;               // 10 = 10% or Rs 10
  readonly amount: number;              // computed currency amount
}

// * Coupon redemption snapshot.
export interface SaleCoupon {
  readonly couponId: string;
  readonly code: string;
  readonly type: 'percent' | 'flat';
  readonly value: number;
  readonly amount: number;              // computed currency amount
}

export interface Sale {
  readonly id: string;
  readonly invoiceNo: string;
  readonly completedAt: Iso8601;
  readonly lines: readonly SaleLine[];
  readonly subtotal: number;
  readonly tax: number;
  readonly total: number;
  readonly unitCount: number;
  readonly paymentMethod: PaymentMethod;   // primary tender - kept for back-compat
  // Set for lending sales AND every online order (customer supplied at checkout).
  readonly customerMobile: string | null;
  // FK to customer entity — set for lending sales + online orders.
  readonly customerId: string | null;
  // Who rang up the sale. For online orders: SYSTEM_ACTOR_ID until staff confirms.
  readonly cashierId: string;
  readonly cashierName: string;
  // Voided sales stay in history for audit.
  readonly voided: boolean;
  readonly voidedAt: Iso8601 | null;
  readonly voidedReason: string | null;
  // Store where the sale happened.
  readonly storeId: string;
  // Physical outlet within storeId. Optional for back-compat with sales *  written before multi-outlet support landed — those default to storeId.
  readonly outletId?: string;

  // -- Online-order fields (all null for counter sales) --------------------
  readonly channel: SaleChannel;
  readonly orderStatus: OrderStatus | null;
  readonly customerName: string | null;
  readonly deliveryAddress: DeliveryAddress | null;
  readonly customerNotes: string | null;
  readonly statusHistory: readonly OrderStatusEvent[] | null;

  // -- Cashier extensions (all optional for back-compat) -----------------
  // * Order type code (dine-in / takeaway / delivery / etc).
  readonly orderTypeCode?: string;
  // * Table (Dine-in only).
  readonly tableId?: string;
  readonly tableCode?: string;
  // * Bill-level discount applied.
  readonly billDiscount?: SaleBillDiscount;
  // * Coupon redeemed.
  readonly coupon?: SaleCoupon;
  // * Sum of every SaleLine.lineDiscount (denormalised for fast reporting).
  readonly lineDiscountTotal?: number;
  // * Additional charges applied to this bill.
  readonly charges?: readonly SaleCharge[];
  // * Split-payment tenders. paymentMethod above is payments[0].method.
  readonly payments?: readonly SalePayment[];
  // * Held-order timestamp. Non-null while the sale is parked; cleared on resume.
  readonly heldAt?: Iso8601 | null;
  // * Sale-level note.
  readonly note?: string;
}

// System actor id for online orders that haven't been touched by staff yet.
export const SYSTEM_ACTOR_ID = '__system__';
export const SYSTEM_ACTOR_NAME = 'Customer (online)';

// Order statuses that are still "in flight" (visible on the Orders Kanban).
export const ACTIVE_ORDER_STATUSES: readonly OrderStatus[] =
  ['placed', 'confirmed', 'packing', 'out_for_delivery'];

// Customers
export interface Customer {
  readonly id: string;
  readonly name: string;
  // 10-digit mobile (digits only). Unique per (storeId, outletId) as of v8.
  readonly mobile: string;
  readonly email: string | null;
  readonly notes: string | null;
  // Outstanding lending balance in currency units.
  readonly lendingBalance: number;
  readonly createdAt: Iso8601;
  // Store that owns this customer record.
  readonly storeId: string;
  // Outlet the customer was registered at (or first visited). Same phone at
  // a different outlet = a new record - branches manage their own CRM.
  // Optional in the type only for back-compat with legacy rows; the v8
  // migration backfills all existing rows and all writes require it.
  readonly outletId?: string;
}

export interface CustomerPayment {
  readonly id: string;
  readonly customerId: string;
  readonly amount: number;
  readonly method: 'cash' | 'card';
  readonly receivedAt: Iso8601;
  readonly receivedBy: string;
  readonly notes: string | null;
}

// Users (staff). Role capabilities live in permissions.ts, not here.
export type UserRole = 'vendor' | 'admin' | 'cashier';

// Sentinel storeId for vendor accounts — they don't belong to any tenant.
export const VENDOR_SCOPE = '__vendor__';

export interface User {
  readonly id: string;
  readonly username: string;
  readonly name: string;
  readonly role: UserRole;
  readonly active: boolean;
  readonly createdAt: Iso8601;
  // Every user belongs to exactly one store.
  readonly storeId: string;
  // Password lives here only because this is a mock/frontend-only build.
  //  When a backend arrives this MUST be moved server-side + hashed (§6).
  readonly password: string;
}

// Subset of User safe to keep in the browser session.
export type SessionUser = Omit<User, 'password'>;

// Settings
export interface StoreSettings {
  readonly storeName: string;
  readonly address: string;
  readonly phone: string;
  readonly gstin: string;
  readonly taxRate: number;
  // ISO 4217 currency code, e.g. USD, INR.
  readonly currency: string;
  readonly receiptFooter: string;
}

// Vendor audit log
// Immutable record of a vendor action across the tenant fleet.
//  Written server-side in production; here we append to a Dexie table.
export type VendorAction =
  | 'tenant.create'
  | 'tenant.edit'
  | 'tenant.suspend'
  | 'tenant.reactivate'
  | 'tenant.impersonate'
  | 'tenant.delete'
  | 'vendor.login'
  | 'vendor.logout';

export interface AuditEntry {
  readonly id: string;
  readonly at: Iso8601;
  readonly actorUsername: string;
  readonly action: VendorAction;
  // storeId the action targeted (may be VENDOR_SCOPE for self-actions).
  readonly targetStoreId: string;
  readonly detail?: string;
}
