// ::: Code Generated by Copilot 7d154f0c-3b26-4d6e-8d85-0b51e380a532. This comment will be removed automatically after the file is saved :::
// FIXTURE - demo product catalog. Scrap when the real backend is live.

// Thematic catalogs per tenant (fashion / restaurant / boutique) so multi-tenancy is obvious.
import type { Product } from '@billing/shared/domain/types';
import {
  SEED_STORE_MAIN_ID, SEED_STORE_BRANCH_ID, SEED_STORE_THIRD_ID,
} from './stores';

const NOW = new Date().toISOString();

const p = (
  id: string, sku: string, name: string, price: number,
  category: Product['category'], tone: Product['tone'], stock: number,
  storeId: string, image?: string,
  outletId?: string,
): Product => ({
  id, sku, name, price, category, tone, stock, active: true, createdAt: NOW,
  storeId,
  // If no outletId is supplied, the fan-out in db-bootstrap will duplicate
  // this row across every outlet of its storeId (shared/base menu). If
  // outletId IS supplied, this product is EXCLUSIVE to that outlet - the
  // fan-out skips it.
  outletId: outletId ?? storeId,
  ...(image && { image }),
});

// Outlet ids (matches SEED_OUTLETS in restaurant.ts). Only exclusives
// hard-code these - everything else fans out via the primary storeId.
const SPICE_KORAM = 'outlet-spice-koram';
const SPICE_HSR   = 'outlet-spice-hsr';

// Velvet Mumbai - luxury Indian fashion
const VELVET: readonly Product[] = [
  p('v01', 'LUX-0001', 'Silk Embroidered Kurta',      3999, 'Personal', 'rose',   20, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400&q=80'),
  p('v02', 'LUX-0002', 'Designer Lehenga Set',       18999, 'Personal', 'rose',    8, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=400&q=80'),
  p('v03', 'LUX-0003', 'Kashmiri Pashmina Shawl',     5499, 'Personal', 'stone',  15, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1551232864-3f0890e580d9?w=400&q=80'),
  p('v04', 'LUX-0004', 'Block Print Co-ord Set',      4999, 'Personal', 'amber',  18, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&q=80'),
  p('v05', 'LUX-0005', 'Handloom Linen Saree',        8999, 'Personal', 'sky',    10, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1594938298603-c8148c4b4057?w=400&q=80'),
  p('v06', 'ACC-0001', 'Zardozi Embroidered Dupatta', 2499, 'Other',    'amber',  25, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1583391733981-8698e2d80fd2?w=400&q=80'),
  p('v07', 'ACC-0002', 'Pearl Drop Earrings',         1999, 'Other',    'amber',  30, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&q=80'),
  p('v08', 'ACC-0003', 'Leather Tote Bag',            6999, 'Other',    'brown',  12, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&q=80'),
  p('v09', 'FTW-0001', 'Kolhapuri Wedges',            2999, 'Other',    'orange', 16, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80'),
  p('v10', 'FTW-0002', 'Embellished Heels',           4499, 'Other',    'rose',   14, SEED_STORE_MAIN_ID, 'https://images.unsplash.com/photo-1596703263926-eb0762ee17e4?w=400&q=80'),
];

// Spice Route Kitchen - Indian non-veg restaurant menu (SHARED across every outlet)
const SPICE_ROUTE: readonly Product[] = [
  p('r01', 'MNU-0001', 'Chicken Biryani Half',          240, 'Biryani', 'yellow', 999, SEED_STORE_BRANCH_ID),
  p('r02', 'MNU-0002', 'Chicken Biryani Full',          380, 'Biryani', 'yellow', 999, SEED_STORE_BRANCH_ID),
  p('r03', 'MNU-0003', 'Mutton Biryani Half',           320, 'Biryani', 'stone',  999, SEED_STORE_BRANCH_ID),
  p('r04', 'MNU-0004', 'Mutton Biryani Full',           520, 'Biryani', 'stone',  999, SEED_STORE_BRANCH_ID),
  p('r05', 'MNU-0005', 'Ghee Rice Half',                140, 'Rice Items', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r06', 'MNU-0006', 'Ghee Rice Full',                220, 'Rice Items', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r07', 'MNU-0007', 'Jeera Rice Half',               120, 'Rice Items', 'orange', 999, SEED_STORE_BRANCH_ID),
  p('r08', 'MNU-0008', 'Jeera Rice Full',               200, 'Rice Items', 'orange', 999, SEED_STORE_BRANCH_ID),
  p('r09', 'MNU-0009', 'Khuska Half',                   150, 'Rice Items', 'brown',  999, SEED_STORE_BRANCH_ID),
  p('r10', 'MNU-0010', 'Khuska Full',                   230, 'Rice Items', 'brown',  999, SEED_STORE_BRANCH_ID),
  p('r11', 'MNU-0011', 'Biryani Khuska Half',           170, 'Rice Items', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r12', 'MNU-0012', 'Biryani Khuska Full',           250, 'Rice Items', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r13', 'MNU-0013', 'Egg Fried Rice Half',           160, 'Rice Items', 'sky',    999, SEED_STORE_BRANCH_ID),
  p('r14', 'MNU-0014', 'Egg Fried Rice Full',           240, 'Rice Items', 'sky',    999, SEED_STORE_BRANCH_ID),
  p('r15', 'MNU-0015', 'Veg Fried Rice Half',           150, 'Rice Items', 'slate',  999, SEED_STORE_BRANCH_ID),
  p('r16', 'MNU-0016', 'Veg Fried Rice Full',           230, 'Rice Items', 'slate',  999, SEED_STORE_BRANCH_ID),
  p('r17', 'MNU-0017', 'Chicken Fried Rice Half',       200, 'Rice Items', 'red',    999, SEED_STORE_BRANCH_ID),
  p('r18', 'MNU-0018', 'Chicken Fried Rice Full',       300, 'Rice Items', 'red',    999, SEED_STORE_BRANCH_ID),
  p('r19', 'MNU-0019', 'Butter Chicken Half',           220, 'Gravies', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r20', 'MNU-0020', 'Butter Chicken Full',           380, 'Gravies', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r21', 'MNU-0021', 'Kadai Chicken Half',            240, 'Gravies', 'orange', 999, SEED_STORE_BRANCH_ID),
  p('r22', 'MNU-0022', 'Kadai Chicken Full',            400, 'Gravies', 'orange', 999, SEED_STORE_BRANCH_ID),
  p('r23', 'MNU-0023', 'Kolhapuri Chicken Half',        230, 'Gravies', 'red',    999, SEED_STORE_BRANCH_ID),
  p('r24', 'MNU-0024', 'Kolhapuri Chicken Full',        390, 'Gravies', 'red',    999, SEED_STORE_BRANCH_ID),
  p('r25', 'MNU-0025', 'Chicken 65 Gravy Half',         250, 'Gravies', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r26', 'MNU-0026', 'Chicken 65 Gravy Full',         410, 'Gravies', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r27', 'MNU-0027', 'Nawabi Murgh Half',             260, 'Gravies', 'brown',  999, SEED_STORE_BRANCH_ID),
  p('r28', 'MNU-0028', 'Nawabi Murgh Full',             420, 'Gravies', 'brown',  999, SEED_STORE_BRANCH_ID),
  p('r29', 'MNU-0029', 'Chicken Tikka Masala Half',     240, 'Gravies', 'slate',  999, SEED_STORE_BRANCH_ID),
  p('r30', 'MNU-0030', 'Chicken Tikka Masala Full',     400, 'Gravies', 'slate',  999, SEED_STORE_BRANCH_ID),
  p('r31', 'MNU-0031', 'Hyderabadi Chicken Gravy Half', 230, 'Gravies', 'sky',    999, SEED_STORE_BRANCH_ID),
  p('r32', 'MNU-0032', 'Hyderabadi Chicken Gravy Full', 390, 'Gravies', 'sky',    999, SEED_STORE_BRANCH_ID),
  p('r33', 'MNU-0033', 'Malai Chicken Half',            250, 'Gravies', 'yellow', 999, SEED_STORE_BRANCH_ID),
  p('r34', 'MNU-0034', 'Malai Chicken Full',            420, 'Gravies', 'yellow', 999, SEED_STORE_BRANCH_ID),
  p('r35', 'MNU-0035', 'Afghani Chicken Half',          240, 'Gravies', 'stone',  999, SEED_STORE_BRANCH_ID),
  p('r36', 'MNU-0036', 'Afghani Chicken Full',          400, 'Gravies', 'stone',  999, SEED_STORE_BRANCH_ID),
  p('r37', 'MNU-0037', 'Parotta',                        70, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r38', 'MNU-0038', 'Kerala Parota',                  80, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r39', 'MNU-0039', 'Celon Parotta',                  90, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r40', 'MNU-0040', 'Special Parota',                 95, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r41', 'MNU-0041', 'Egg Parota',                     85, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r42', 'MNU-0042', 'Kheema Parota',                110, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r43', 'MNU-0043', 'Tandoori Roti',                  70, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r44', 'MNU-0044', 'Butter Naan',                    90, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r45', 'MNU-0045', 'Butter Roti',                    70, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r46', 'MNU-0046', 'Kulcha',                         90, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r47', 'MNU-0047', 'Rumaali Roti',                   70, 'Parotta & Roti', 'amber',  999, SEED_STORE_BRANCH_ID),
  p('r48', 'MNU-0048', 'Shawarma',                      180, 'Rolls', 'red',    999, SEED_STORE_BRANCH_ID),
  p('r49', 'MNU-0049', 'Nizam Roll',                    190, 'Rolls', 'red',    999, SEED_STORE_BRANCH_ID),
  p('r50', 'MNU-0050', 'Chicken Roll',                  180, 'Rolls', 'red',    999, SEED_STORE_BRANCH_ID),
  p('r51', 'MNU-0051', 'Chicken Sheek Roll',            200, 'Rolls', 'red',    999, SEED_STORE_BRANCH_ID),
  p('r52', 'MNU-0052', 'Mutton Sheek Roll',             220, 'Rolls', 'red',    999, SEED_STORE_BRANCH_ID),
  p('r53', 'MNU-0053', 'Chicken Kebab',                 220, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r54', 'MNU-0054', 'Sholay Kebab',                  230, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r55', 'MNU-0055', 'Chicken Lolipop',               240, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r56', 'MNU-0056', 'Pudina Kebab',                  220, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r57', 'MNU-0057', 'Lemon Kebab',                   210, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r58', 'MNU-0058', 'Chicken Sheek Kebab',           230, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r59', 'MNU-0059', 'Mutton Sheek Kebab',            250, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r60', 'MNU-0060', 'Kalmi Kebab',                   240, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r61', 'MNU-0061', 'Bhuna Kebab',                   230, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r62', 'MNU-0062', 'Shashlik Kebab',                240, 'Kebabs', 'rose',   999, SEED_STORE_BRANCH_ID),
  p('r63', 'MNU-0063', 'Chicken Tandoori',              260, 'Tandoori Items', 'orange', 999, SEED_STORE_BRANCH_ID),
  p('r64', 'MNU-0064', 'Reshmi Kebab',                  220, 'Tandoori Items', 'orange', 999, SEED_STORE_BRANCH_ID),
  p('r65', 'MNU-0065', 'Banjara Kebab',                 230, 'Tandoori Items', 'orange', 999, SEED_STORE_BRANCH_ID),
  p('r66', 'MNU-0066', 'Malai Kebab',                   220, 'Tandoori Items', 'orange', 999, SEED_STORE_BRANCH_ID),
  p('r67', 'MNU-0067', 'Double Dum Kebab',              240, 'Tandoori Items', 'orange', 999, SEED_STORE_BRANCH_ID),
];

// Koramangala EXCLUSIVES - trendy fusion menu targeting the tech crowd
const SPICE_KORAM_EXCL: readonly Product[] = [
  p('r-km-01', 'KRM-0001', 'Butter Chicken Pizza',     520, 'Meat',      'red',    999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400&q=80', SPICE_KORAM),
  p('r-km-02', 'KRM-0002', 'Korean Gochujang Wings',   440, 'Snacks',    'orange', 999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=400&q=80', SPICE_KORAM),
  p('r-km-03', 'KRM-0003', 'Kimchi Fried Rice',        380, 'Other',     'amber',  999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=400&q=80', SPICE_KORAM),
  p('r-km-04', 'KRM-0004', 'Chai Cheesecake',          240, 'Other',     'brown',  999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&q=80', SPICE_KORAM),
  p('r-km-05', 'KRM-0005', 'Cold Brew Coffee',         180, 'Beverages', 'stone',  999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&q=80', SPICE_KORAM),
];

// HSR Layout EXCLUSIVES - health-first menu with millets and grain bowls
const SPICE_HSR_EXCL: readonly Product[] = [
  p('r-hs-01', 'HSR-0001', 'Millet Chicken Biryani',   480, 'Other',     'yellow', 999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400&q=80', SPICE_HSR),
  p('r-hs-02', 'HSR-0002', 'Ragi Roti Thali',          340, 'Other',     'brown',  999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1567337710282-00832b415979?w=400&q=80', SPICE_HSR),
  p('r-hs-03', 'HSR-0003', 'Quinoa Prawn Bowl',        520, 'Meat',      'sky',    999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80', SPICE_HSR),
  p('r-hs-04', 'HSR-0004', 'Beetroot Kebab Platter',   360, 'Snacks',    'rose',   999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&q=80', SPICE_HSR),
  p('r-hs-05', 'HSR-0005', 'Turmeric Almond Latte',    160, 'Beverages', 'amber',  999, SEED_STORE_BRANCH_ID, 'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=400&q=80', SPICE_HSR),
];

// La Maison Boutique - luxury fashion, SoHo New York
const LA_MAISON: readonly Product[] = [
  p('b01', 'BTQ-0001', 'Italian Merino Blazer',       389, 'Personal', 'slate',  8,  SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=400&q=80'),
  p('b02', 'BTQ-0002', 'French Linen Dress',          289, 'Personal', 'sky',    12, SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=400&q=80'),
  p('b03', 'BTQ-0003', 'Cashmere Turtleneck',         249, 'Personal', 'stone',  15, SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400&q=80'),
  p('b04', 'BTQ-0004', 'Wide-Leg Silk Trousers',      329, 'Personal', 'amber',  10, SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=400&q=80'),
  p('b05', 'BTQ-0005', 'Leather Crossbody Bag',       459, 'Other',    'brown',   7, SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&q=80'),
  p('b06', 'BTQ-0006', 'Suede Chelsea Boots',         399, 'Other',    'brown',   9, SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=400&q=80'),
  p('b07', 'BTQ-0007', 'Gold Chain Necklace',         189, 'Other',    'amber',  20, SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&q=80'),
  p('b08', 'BTQ-0008', 'Silk Square Scarf',           159, 'Other',    'rose',   25, SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1584030373081-f37b7bb4fa8e?w=400&q=80'),
  p('b09', 'BTQ-0009', 'Canvas Tote Bag',              89, 'Other',    'sky',    30, SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&q=80'),
  p('b10', 'BTQ-0010', 'Structured Wool Coat',        549, 'Personal', 'slate',   6, SEED_STORE_THIRD_ID, 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=400&q=80'),
];

export const SEED_PRODUCTS: readonly Product[] = [
  ...VELVET,
  ...SPICE_ROUTE, ...SPICE_KORAM_EXCL, ...SPICE_HSR_EXCL,
  ...LA_MAISON,
];
