/**
 * All user-facing copy lives here (§1, §11).
 * Sentence case for actions, Title Case for headings.
 * Error messages start with what happened, not user blame.
 */

export const STRINGS = {
  brand: {
    name:    'Walmart',
    tagline: 'Save money. Live better.',
  },

  nav: {
    cashier:    'Cashier',
    dashboard:  'Dashboard',
    sales:      'Sales',
    customers:  'Customers',
    products:   'Products',
    users:      'Staff',
    settings:   'Settings',
    logout:     'Log out',
    register:   'Register #01',
    account:    'Account',
  },

  auth: {
    loginTitle:     'Sign in to your store',
    loginSubtitle:  'Enter your credentials to continue.',
    username:       'Username',
    password:       'Password',
    signIn:         'Sign in',
    signingIn:      'Signing in…',
    demoHint:       'Demo · admin / admin123  ·  cashier / cashier123',
    invalid:        'Invalid username or password.',
    inactive:       'This account is inactive. Contact your admin.',
    loggedOut:      'You have been signed out.',
    sessionExpired: 'Your session has expired. Please sign in again.',
  },

  cashier: {
    pageTitle:        'Cashier Terminal',
    pageSubtitle:     'Ring up items and check out customers.',
    searchPlaceholder:'Search by product name…',
    clearSearch:      'Clear search',
    emptyResults:     'No products match your search.',
    emptyResultsHint: 'Try a different keyword or category.',
    addToCart:        'Add',
    inStock:          'In stock',
    lowStock:         'Low',
    cartTitle:        'Current Sale',
    cartEmpty:        'Cart is empty',
    cartEmptyHint:    'Tap a product on the left to add it.',
    clearCart:        'Clear',
    charge:           'Charge',
    itemsSuffix:      'items',
    itemSuffix:       'item',
    decreaseQty:      'Decrease quantity',
    increaseQty:      'Increase quantity',
    removeLine:       'Remove item',
    subtotal:         'Subtotal',
    tax:              'Tax',
    total:            'Total',
  },

  payment: {
    heading:            'Choose payment method',
    subheading:         'Select how the customer will pay.',
    methodCash:         'Cash',
    methodCashHint:     'Pay with physical currency.',
    methodCard:         'Card',
    methodCardHint:     'Debit or credit card.',
    methodLending:      'Lending',
    methodLendingHint:  'Buy now, pay later — mobile required.',
    mobileLabel:        'Customer mobile number',
    mobileHint:         '10-digit number for lending record & receipt.',
    mobileError:        "That doesn't look like a valid 10-digit number.",
    cancel:             'Cancel',
    submit:             'Complete sale',
    submitting:         'Processing…',
  },

  receipt: {
    successHeading: 'Payment successful',
    successBody:    'The sale has been recorded.',
    invoice:        'Invoice',
    customer:       'Customer',
    payment:        'Payment method',
    dateLabel:      'Date',
    itemsSold:      'Items sold',
    uniqueItems:    'Unique items',
    totalUnits:     'Total units',
    amountPaid:     'Amount paid',
    thankYou:       'Thank you for shopping with us.',
    returnPolicy:   'Returns accepted within 90 days with this receipt.',
    print:          'Print receipt',
    newSale:        'Start new sale',
  },

  dashboard: {
    pageTitle:      'Sales Dashboard',
    pageSubtitle:   'Live view of everything sold today.',
    kpiRevenue:     'Revenue today',
    kpiSales:       'Sales completed',
    kpiUnits:       'Units sold',
    kpiUniqueSku:   'Unique SKUs',
    kpiLendingWO:   'Lending balance',

    recentSalesTitle:     'Recent sales',
    recentSalesEmpty:     'No sales yet — head to the Cashier to ring one up.',
    columnInvoice:        'Invoice',
    columnTime:           'Time',
    columnItems:          'Items',
    columnPayment:        'Payment',
    columnCustomer:       'Customer',
    columnTotal:          'Total',

    topProductsTitle:  'Top-selling products',
    topProductsEmpty:  'No products sold yet.',
    columnRank:        '#',
    columnProduct:     'Product',
    columnSold:        'Units sold',
    columnRevenue:     'Revenue',

    inventoryTitle:    'Inventory movement',
    inventoryEmpty:    'No inventory movement yet.',
    columnSku:         'SKU',
    columnCategory:    'Category',
    columnStock:       'Stock left',
    columnMovement:    'Sold today',
  },

  products: {
    pageTitle:     'Products',
    pageSubtitle:  'Manage your product catalog and stock levels.',
    addNew:        'Add product',
    editHeading:   'Edit product',
    createHeading: 'Add a new product',
    empty:         'No products yet.',
    emptyHint:     'Click “Add product” to get started.',
    columnSku:     'SKU',
    columnName:    'Name',
    columnPrice:   'Price',
    columnStock:   'Stock',
    columnStatus:  'Status',
    active:        'Active',
    inactive:      'Inactive',
    edit:          'Edit',
    deactivate:    'Deactivate',
    activate:      'Activate',
    fieldSku:      'SKU',
    fieldName:     'Name',
    fieldPrice:    'Price',
    fieldStock:    'Stock',
    fieldCategory: 'Category',
    fieldTone:     'Colour tone',
    save:          'Save',
    saving:        'Saving…',
    saved:         'Product saved.',
    deleteConfirm: 'Deactivate this product? It will be hidden from the Cashier terminal.',
    duplicateSku:  'A product with that SKU already exists.',
  },

  customers: {
    pageTitle:      'Customers',
    pageSubtitle:   'Look up shoppers, track lending balances, record payments.',
    addNew:         'Add customer',
    createHeading:  'Add a new customer',
    editHeading:    'Edit customer',
    empty:          'No customers yet.',
    emptyHint:      'Add one, or the next Lending sale will create one automatically.',
    columnName:     'Name',
    columnMobile:   'Mobile',
    columnEmail:    'Email',
    columnBalance:  'Lending balance',
    columnSince:    'Customer since',
    columnActions:  'Actions',
    view:           'View',
    edit:           'Edit',
    fieldName:      'Name',
    fieldMobile:    'Mobile',
    fieldEmail:     'Email (optional)',
    fieldNotes:     'Notes (optional)',
    save:           'Save',
    duplicateMobile:'A customer with that mobile already exists.',
    searchPlaceholder:'Search by name or mobile…',
    detailTitle:     'Customer profile',
    balanceHeading:  'Outstanding lending balance',
    recordPayment:   'Record a payment',
    recordPaymentHint:'Enter the amount the customer just paid to reduce their balance.',
    paymentAmount:   'Amount paid',
    paymentMethod:   'Method',
    paymentNotes:    'Notes (optional)',
    submitPayment:   'Record payment',
    paymentSuccess:  'Payment recorded.',
    paymentTooHigh:  'Amount exceeds the outstanding balance.',
    paymentInvalid:  'Enter a valid amount greater than 0.',
    paymentHistory:  'Payment history',
    paymentEmpty:    'No payments recorded yet.',
    saleHistory:     'Sale history',
    saleHistoryEmpty:'No sales recorded for this customer yet.',
    backToList:      'All customers',
  },

  sales: {
    pageTitle:    'Sales history',
    pageSubtitle: 'Every sale, filterable, exportable, voidable.',
    empty:        'No sales recorded yet.',
    emptyHint:    'Head to the Cashier to ring one up.',
    filterAll:    'All',
    filterCash:   'Cash',
    filterCard:   'Card',
    filterLending:'Lending',
    filterVoided: 'Voided only',
    filterActive: 'Not voided',
    view:         'View',
    void:         'Void',
    voidHeading:  'Void this sale?',
    voidHint:     'The sale stays in history for audit but stops counting towards revenue.',
    voidReason:   'Reason (required)',
    voidConfirm:  'Void sale',
    voidedBadge:  'Voided',
    voidSuccess:  'Sale voided.',
    detailTitle:  'Sale detail',
    backToList:   'All sales',
  },

  users: {
    pageTitle:      'Staff',
    pageSubtitle:   'Manage who can access the terminal.',
    addNew:         'Invite user',
    createHeading:  'Invite a new user',
    editHeading:    'Edit user',
    empty:          'No staff yet — invite your first cashier.',
    columnName:     'Name',
    columnUsername: 'Username',
    columnRole:     'Role',
    columnStatus:   'Status',
    columnActions:  'Actions',
    fieldName:      'Full name',
    fieldUsername:  'Username',
    fieldPassword:  'Password',
    fieldRole:      'Role',
    roleAdmin:      'Admin',
    roleCashier:    'Cashier',
    active:         'Active',
    inactive:       'Inactive',
    edit:           'Edit',
    deactivate:     'Deactivate',
    activate:       'Activate',
    save:           'Save',
    duplicateUser:  'That username is already in use.',
    weakPassword:   'Password must be at least 8 characters.',
    cannotDeactivateSelf: 'You cannot deactivate your own account.',
    forbidden:      'Only admins can manage staff.',
  },

  settings: {
    pageTitle:     'Settings',
    pageSubtitle:  'Store info, tax, currency, receipt template.',
    save:          'Save changes',
    saved:         'Settings saved.',
    storeName:     'Store name',
    address:       'Address',
    phone:         'Phone',
    gstin:         'Tax ID / GSTIN',
    taxRate:       'Tax rate (%)',
    currency:      'Currency (ISO 4217)',
    receiptFooter: 'Receipt footer message',
    dangerHeading: 'Danger zone',
    dangerHint:    'Wipe all locally stored data. Only affects this browser.',
    wipeAll:       'Reset all local data',
    wipeConfirm:   'This will delete all sales, customers, products and settings from this browser. Continue?',
    wipeDone:      'All local data cleared. Reloading…',
    forbidden:     'Only admins can change settings.',
  },

  common: {
    save:    'Save',
    cancel:  'Cancel',
    close:   'Close',
    delete:  'Delete',
    confirm: 'Confirm',
    yes:     'Yes',
    no:      'No',
    back:    'Back',
    loading: 'Loading…',
  },

  errors: {
    generic:        'Something went wrong. Try again.',
    emptyCart:      'Add at least one product before charging.',
    mobileRequired: 'Mobile number is required for lending sales.',
    outOfStock:     'Not enough stock available.',
    notFound:       'That record no longer exists.',
    forbidden:      "You don't have permission to do that.",
  },

  ariaLabels: {
    openCart:         'Open cart',
    closePayment:     'Close payment dialog',
    closeReceipt:     'Close receipt dialog',
    navigate:         'Primary navigation',
    userMenu:         'Account menu',
    closeModal:       'Close dialog',
  },
} as const;
